version: "3.8"
services:
  frontend:
    build: ./fe-dumbmerch
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./be-dumbmerch
    container_name: backend-container
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: "postgres"
    container_name: database-container
    environment:
      - POSTGRES_USER=mahesa
      - POSTGRES_PASSWORD=Mahesa123
      - POSTGRES_DB=dumbmerch
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: unless-stopped

